### ISSUE TITLE
Add dependency caching for faster builds

### ISSUE THREAD

**Issue by guilatrova** [guilatrova/tryceratops#40]
```yaml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-python@v2
  with:
    python-version: '3.9'
    cache: 'pip'
- run: pip install -r requirements.txt
- run: pip test
```

Question: It should work fine with poetry, right ?

Reference: https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching/
